version: '3.9'

services:
  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lanchonete
  
  wordpress:
    depends_on:
      - db
    image: 'gerenciador-pedidos:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lanchonete
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATARSOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

