server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL}:5432/lanchonete?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: ${DB_USER}
    password: ${DB_PASS}
#    url: jdbc:postgresql://localhost:5432/lanchonete?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
#    username: postgres
#    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      show-sql: true
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true

  springdoc:
    api-docs:
      enabled: true
